// <auto-generated />
using BtEntityFramework.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BtEntityFramework.Migrations
{
    [DbContext(typeof(BTDbContext))]
    [Migration("20220111161556_CreateBTDb")]
    partial class CreateBTDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BtEntityFramework.Models.Persoane", b =>
                {
                    b.Property<int>("PersoanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumePersoana")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("PersoanaId");

                    b.ToTable("Persoane");
                });

            modelBuilder.Entity("BtEntityFramework.Models.Produse", b =>
                {
                    b.Property<int>("ProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeProdus")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("ProdusId");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("BtEntityFramework.Models.Remuneratii", b =>
                {
                    b.Property<int>("RemuneratieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<int>("Luna")
                        .HasColumnType("int");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Remuneratie")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RemuneratieId");

                    b.HasIndex("ProdusId");

                    b.ToTable("Remuneratii");
                });

            modelBuilder.Entity("BtEntityFramework.Models.Vanzari", b =>
                {
                    b.Property<int>("VanzareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<int>("Luna")
                        .HasColumnType("int");

                    b.Property<int>("NrProduse")
                        .HasColumnType("int");

                    b.Property<int>("PersoanaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.HasKey("VanzareId");

                    b.HasIndex("PersoanaId");

                    b.HasIndex("ProdusId");

                    b.ToTable("Vanzari");
                });

            modelBuilder.Entity("BtEntityFramework.Models.Remuneratii", b =>
                {
                    b.HasOne("BtEntityFramework.Models.Produse", "Produs")
                        .WithMany("Remuneratii")
                        .HasForeignKey("ProdusId")
                        .HasConstraintName("FK_Remuneratii_Produse")
                        .IsRequired();
                });

            modelBuilder.Entity("BtEntityFramework.Models.Vanzari", b =>
                {
                    b.HasOne("BtEntityFramework.Models.Persoane", "Persoana")
                        .WithMany("Vanzari")
                        .HasForeignKey("PersoanaId")
                        .HasConstraintName("FK_Vanzari_Persoane")
                        .IsRequired();

                    b.HasOne("BtEntityFramework.Models.Produse", "Produs")
                        .WithMany("Vanzari")
                        .HasForeignKey("ProdusId")
                        .HasConstraintName("FK_Vanzari_Produse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
